name: Distributed CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-distributed:
    #if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-ci') }}
    runs-on: [self-hosted, linux, gpu]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Install dependencies
        env:
          UPDATE_PIP: 'true'
        run: |
          rm -rf .dacecache tests/.dacecache
          . /opt/setupenv
          make clean install
          venv/bin/pip install mpi4py

      - name: Run Distributed Tests
        env:
          PYTEST: venv/bin/coverage run --parallel-mode --source=daceml -m pytest 
          PYTEST_ARGS: -s
          PYTEST_PLUGINS: tests.distributed.mpi_mute
          MPI_PREFIX: mpirun -np 8 --oversubscribe
        run: make test-distributed

      - name: Upload coverage
        run: make codecov
